### ISSUE TITLE
Question about constructors

### ISSUE THREAD

**Issue by arjarn** [olton/m4q#1]
I'm testing m4q and seem good way ;)
But I've question about this part :

```
$("<div>", context) - create in context
$("<div>any_text_or_html</div>") - create by html
```

All my attempts to use it are... bad. 
Nothing new in my page.

Could you help me with more indications about it ?

Thanx for your job and have a good new year (first off all : health and in second more money for your time with m4).

**Comment by olton** [comment]
after creating an element you must add it to the DOM with one of the methods: append, appendTo, ... These methods defined in the https://github.com/olton/m4q/blob/master/src/manipulation.js

**Comment by olton** [comment]
I'm wondering if our need a call to $ ("<div>", context). Perhaps with such a call, you need to immediately insert an element into the context?

**Comment by arjarn** [comment]
Sorry for delay, ok I understand how use it.
I'm making mistake and think it insert immediately.

**Comment by olton** [comment]
now - `$("<div>", context)` - create by rule and add to context, if context is a element
