### ISSUE TITLE
The function of the loop was not found

### ISSUE THREAD

**Issue by chongzia** [olton/m4q#2]
1. The process of using the project on a small scale,no circulatory function was found.
Maybe because it's not finished yet.

2. It should have complete "window" operation functions such as screen size, etc.

3. Ajax should have processing capabilities for file requests.

4. It has perfect operation ability of document information, and can obtain information content such as audio, video, image and document.

5. Uniform format, or unique format, should be proposed prematurely to make the operation simpler than JQ. 
Avoid diversified code formats as much as possible. Each scheme should have unique operability and reduce the difficulty of learning.

6. Hope to create great works，Hope it works better than JQ

**Comment by olton** [comment]
`The function of the loop was not found` Did not quite understand what you mean :(

**Comment by olton** [comment]
You can send files with existing methods.
```
var data = new FormData();
data.append(...);
$.post(
   "https://yousite.com",
   data,
   function(){ // onsuccess
   } 
)
```

**Comment by chongzia** [comment]
Before these updates，Document description for not found  loops ，Now there's this explanation.
For example, the most basic way to get the width and height of the window, and to maintain the position of a div in the scrolling process, etc.


After that, I think this project still lacks the operation of window objects.
Secondly, it is considered that there should be some functional operations for uploading files, such as obtaining specific information of changing files, such as changing the absolute path of the local hard disk of the files, such as the length of video playback, and so on. These parameters can be directly obtained by the user through simple encapsulation to complete the operation of the complete document node.

**Comment by chongzia** [comment]
I really is did like tha
lead into other class libraries
http://prototypejs.org/learn/element-layout.html



But I think you're God Almighty
I don't know why I feel this way.
But in this career of coding
From the bottom of my heart, I do think so.

**Comment by olton** [comment]
You can use `$(el).style()` - get inline styles or computed, `$(el).style(prop_name)` to get inline or computed style property

**Comment by olton** [comment]
To get size and position:
- `$(...).height( )`
- `$(...).height( val )`
- `$(...).width( )`
- `$(...).width( val )`
- `$(...).outerHeight( )`
- `$(...).outerHeight( val )`
- `$(...).outerWidth( )`
- `$(...).outerWidth( val )`
- `$(...).offset( )`
- `$(...).position( excludeMargin )`
